### PR TITLE
Add connect and reconnect methods to MQTTClient

### PR DESCRIPTION
**Pull request by hankbao**
- Expose connect and reconnect methods
- Mark serialQueue in MQTTClient as private (as it's not used outside anymore)
- Remove redundant brackets in if statements

### CODE REVIEW

**Comment by flightonary** [comment]
Moscapsule based on the concept that instance of MQTTClient is disposable object, i.e. 
it is created on demand and discarded when mqtt connection is no longer needed.
Therefore it is not provided implements to expose connect, reconnect and disconnect methods.

**Comment by hankbao** [comment]
This is interesting. But I'd still argue that in some circumstance the disposing and re-initializing of a MQTTClient to make it disconnect and then reconnect is some kind of extra overhead that may not be necessary.

For example, for messaging apps, there'd usually be a MQTTClient to handle incoming and outgoing messages. It's very common to disconnect when the remote host is unreachable and to reconnect when it's reachable again as the network condition changes frequently for mobile devices. In addition, it's also required to disconnect and reconnect when switching app between foreground and background.

On the other hand, providing connect / reconnect methods will not prevent users from using MQTTClient as a disposable object. It just extends the possible scenarios while disconnect method has already been public to users.

**Comment by flightonary** [comment]
OK.
But disconnect method should be also exposed in order to stop automatic reconnecting.
I'll do it later.

**Comment by hankbao** [comment]
Thanks.

**Pull request merged**
